apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gym-investire-backoffice-web
  namespace: ns-neotech-devops
spec:
  project: neotech-coll
  destination:
    name: in-cluster
    namespace: ns-gym-investire-coll
  source:
    repoURL: https://github.com/neotech-projects/web-gym-backoffice.git
    path: k8s/overlays/coll
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
