apiVersion: v1
kind: Service
metadata:
  name: srv-gym-investire-backoffice-web-coll
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gym-investire-backoffice-web-coll
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
