apiVersion: v1
kind: Service
metadata:
  name: srv-demo-fe
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: demo-fe
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
